### ISSUE TITLE
WiFi Signal Strength Indication

### ISSUE THREAD

**Issue by Matt86C** [enwi/RNGBridgeDoc#12]
**Is your feature request related to a problem? Please describe.**
I have the RNGBridge running in a garden shed which has patchy WiFi. Having some feedback on the WiFI signal strength via MQTT would help a lot with positioning the unit.

**Describe the solution you'd like**
MQTT topic including WiFi signal strength. Ideally also an indication of this on the web UI.

**Describe alternatives you've considered**
The alternative is blindly adjusting RNGBridge location and looking to see if WiFI connection is lost in Home Assistant.

**Additional context**
I use an ESP for controlling my boiler using the following project. This integrates with home assistant really well and might be a useful reference case. https://github.com/emsesp/EMS-ESP

**Comment by enwi** [comment]
Sure, this can be added fairly easy

**Comment by enwi** [comment]
New version coming soon:
![temp](https://user-images.githubusercontent.com/25170066/182886766-e2fd86df-5b01-4507-95db-35d5493f4b34.png)

**Comment by enwi** [comment]
Added with [V2.7.2](https://github.com/enwi/RNGBridgeDoc/releases/tag/2.7.2)

**Comment by Matt86C** [comment]
Amazing, thanks for the quick turn around!

**Comment by enwi** [comment]
You are welcome 🙂
