### ISSUE TITLE
RJ12 cable

### ISSUE THREAD

**Issue by pmknowles** [enwi/RNGBridgeDoc#14]
Built the kit from Tindie. For the RJ12 do all the pins need to be connected? Is the cable straight through or crossed or what?

**Comment by enwi** [comment]
@pmknowles Yes all pins need to be connected and it needs to be a straight one. Here are some pictures to help.
![straight vs reverse](https://cdn.discordapp.com/attachments/817428574507761784/932682636302876732/pasted_image_0.jpg)
![pinout](https://cdn.discordapp.com/attachments/817428574507761784/932682636017676348/RS232.jpg)

**Comment by pmknowles** [comment]
Thanks

Regards,

Phil
