### ISSUE TITLE
More parameters for load control/output 1/2/3 control

### ISSUE THREAD

**Issue by Doggy77** [enwi/RNGBridgeDoc#9]
I would like to switch the outputs depending on the fact if it's getting dark: Switch automatically on the lights if the panels don't harvest energy, or make the pond pump work only when it's sunny/day.

Therefore an additional parameter (aside from Battery Voltage or Battery SOC) for controlling the behaviour of the outputs would be great: Panel Current (independent from the count of modules) or panel voltage would be great additions in my opinion.

**Comment by enwi** [comment]
Panel current and panel voltage control parameters added with [release 2.6.0](https://github.com/enwi/RNGBridgeDoc/releases/tag/2.6.0)
